@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoid2Fzc29tQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiLCJBRE1JTiIsIk1BTkFHRVIiLCJTQUxFUyIsIlNBTEVTX01BTkFHRVIiLCJWT0xUIiwiVk9MVF9NQU5BR0VSIiwiUkgiLCJBQ0NPVU5UQU5UIiwiRFJJVkVSIiwiU1VQRVJBRE1JTiJdLCJpYXQiOjE3ODU0MTQ3MjMsImV4cCI6MTc4NTUwMTEyM30.Rl12fSOJ6zmqxDvvAW3eeUtqqvNkobNgpzo_YQyFbq8

### login
POST http://localhost:5000/api/v1.0.0/base/user/login
Content-Type: application/json

{
    "email": "wassom@gmail.com",
    "password": "1234567"
}

###
GET http://localhost:5002/api/v1.0.0/request/payment/expenses/all?pageIndex=1&pageSize=15&tab=validated&amount=0&amountType=greater
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1.0.0/request/payment/paymentToSign/all?pageIndex=0&pageSize=15&tab=pending&amount=0&amountType=greater
Authorization: Bearer {{token}}

###
GET https://api.creaconsult-app.com/api/v1.0.0/request/payment/expenses/dg
Authorization: Bearer {{token}}