@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoid2Fzc29tQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiLCJBRE1JTiIsIk1BTkFHRVIiLCJTQUxFUyIsIlNBTEVTX01BTkFHRVIiLCJWT0xUIiwiVk9MVF9NQU5BR0VSIiwiUkgiLCJBQ0NPVU5UQU5UIiwiRFJJVkVSIiwiU1VQRVJBRE1JTiJdLCJpYXQiOjE3ODcyMzQxNzUsImV4cCI6MTc4NzMyMDU3NX0.Ww2b2KJxTajXDtWqs3e4F2CvKfHQA95jfi3Vzu4XJJw

### login
POST http://localhost:5000/api/v1.0.0/base/user/login
Content-Type: application/json

{
    "email": "wassom@gmail.com",
    "password": "1234567"
}

###
GET http://localhost:5002/api/v1.0.0/request/payment/expenses/all?pageIndex=1&pageSize=15&tab=validated&amount=0&amountType=greater
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1.0.0/request/payment/paymentToSign/all?pageIndex=0&pageSize=15&tab=pending&amount=0&amountType=greater
Authorization: Bearer {{token}}

###
GET https://api.creaconsult-app.com/api/v1.0.0/request/payment/expenses/dg
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1.0.0/request/vehicle/stats?date=custom&from=2026-08-01&to=2026-08-05
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1.0.0/request/devi/element/
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1.0.0/request/devi/
Authorization: Bearer {{token}}

###
DELETE http://localhost:5000/api/v1.0.0/request/devi/reject/63
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1.0.0/request/object/354
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1.0.0/request/object/chief/requests/count
Authorization: Bearer {{token}}