-- AlterTable
ALTER TABLE "Payment" ADD COLUMN     "crearedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dateline" TIMESTAMP(3),
ADD COLUMN     "method" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
